Thunderbird 128.4.4esr
pop-os/packaging-thunderbird pull request #16
Opened 2024-11-19 14:51 UTC by leviport

* https://www.mozilla.org/en-US/thunderbird/128.4.4esr/releasenotes/
* https://hg.mozilla.org/releases/comm-esr128/log/e963642f77edeb0a8a39ffdca4c7f2dee69f0b78

2024-11-19 16:33 UTC, jacobgkau requested changes
Again, this did not build because the SHA256SUMS file was replaced with a 404 page.

https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/128.4.4esr/SHA256SUMS does not 404 now, so at least the delay to get that working wasn't as long as it was last time.

2024-11-19 16:40 UTC, jacobgkau commented
I wonder if the Firefox maintainers have a longer delay between when they upload release notes and when they send out a notification e-mail, since we have to use a third-party tool to monitor the RSS feed directly for Thunderbird's release notes. I know there've been times when they've taken a little while to send the Firefox announcement email out.

2024-11-19 22:34 UTC, jacobgkau approved these changes

2024-11-22 16:35 UTC, wash2 approved these changes

2024-11-22 17:19 UTC, merged